ARG BALENA_ARCH=%%BALENA_ARCH%%

# base
FROM balenalib/${BALENA_ARCH}-alpine-node:16.13-run as base

WORKDIR /opt

COPY package*.json ./

# build
FROM base as build

COPY tsconfig*.json ./
COPY src ./src
COPY typings ./typings

RUN JOBS=MAX npm install --unsafe-perm && npm cache clean --force && rm -rf /tmp/*
RUN npm run build

# -- Run --
FROM base as run

RUN apk add dbus-glib-dev

RUN JOBS=MAX npm ci --only=production --unsafe-perm \
    && npm cache clean --force \
    && rm -rf /tmp/*

COPY --from=build /opt/build/ ./build/

CMD ["npm", "start"]
